### ISSUE TITLE
Add boilerplate

### ISSUE THREAD

**Issue by Zeitsperre** [hydrologie/xhydro-lstm#1]
@hydrologie/xhydro-developers 

In order to get this started, there are some changes that need to be finalized in the cookiecutter template (https://github.com/Ouranosinc/cookiecutter-pypackage). Final validation and merge is required. Once that is in, I can make the boilerplate.

Some clarifications:
- Who wishes to be listed as author(s)/maintainer(s)? (Myself listed as a backup maintainer)
- License? (Apache v2.0 by default)
- Documentation? (yes)
- Tests? (no?)

**Comment by RondeauG** [comment]
@richardarsenault should be listed as the main author. I can be added as a maintainer if you want someone else to do admin stuff like accepting PRs.

**Comment by RondeauG** [comment]
Just in case, your other assumptions were good.

- License? (Apache v2.0 by default)
- Documentation? (yes)
- Tests? (no?)
